### ISSUE TITLE
payment does not work on PI wallet

### ISSUE THREAD

**Issue by wrramerson** [rockcesar/LatinChainDevelopments#4]
when you open the payment window the time runs out and the payment is not confirmed

**Comment by rockcesar** [comment]
We are on Mainnet, already configured in our App. But we have to wait until our developers obtain Pi Mainnet wallet, in order to receive Mainnet payments.

We are working on setting up our App, so we can have full access on Mainnet.

Watch this tweet:
https://twitter.com/LatinChainLatam/status/1553477715600281603?t=56T6JDsKNtQq2LqH0b0KQA&s=19

Also join the Social Networks which appears on: https://latin-chain.com

Thanks.

**Comment by rockcesar** [comment]
Refer to this issue:

https://github.com/rockcesar/LatinChainDevelopments/issues/5

And check this helping page:

https://github.com/rockcesar/LatinChainDevelopments/tree/master/docs-firstapp#simplest-example-for-user2app-payment
